leetcode/frontend/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('problems/', views.add_code, name='add_code'),
    path('', views.home, name='home')
]

leetcode/leetcode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls'))
]

leetcode/frontend/models.py
from django.db import models

# Create your models here.
class Code(models.Model):
    title = models.CharField(max_length=250)
    program = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

leetcode/frontend/forms.py
from django import forms
from .models import Code


class CodeForm(forms.ModelForm):

    class Meta:
        model = Code
        fields = ('title', 'program')
        widget = {
            'program': forms.Textarea(),
        }

leetcode/backend/views.py
from django.shortcuts import render

# Create your views here.

leetcode/frontend/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Code
from .forms import CodeForm

def home(request):
    return HttpResponse("HOME")

# Create your views here.
def add_code(request):
    if request.method == "POST":
        form = CodeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Program added')
        else:
            return HttpResponse('not valid')
    else:
        form = CodeForm()
    return render(request, 'code_editor/add_code.html', {'code_form': form})

leetcode/templates/assist/ask_question_temp.html
<div class="d-flex justify-content-end my-3">
    <a href="/ask" class="btn btn-outline-primary">Ask Question</a>
</div>

leetcode/templates/assist/header.html
<header class="container-fluid p-0" style="background:#eee; height: 65px;">
    <div class="container d-flex justify-content-between align-items-center p-2">
        <a href="{% url 'home' %}" class="navbar-brand mr-auto p-2">Stack Overflow</a>
        <form action="" method="POST" class="d-flex justify-content-center align-items-center">
            {% csrf_token %}
            <input type="search" class="form-control form-control-sm me-2"  placeholder="Search Question" aria-label="Search" name="search" id="search">
            <input type="submit" class="btn btn-outline-success btn-sm" value="Search">
        </form>

        <div class="d-flex align-items-center justify-content-center">
            {% if request.user.is_authenticated %}
            <p class="mb-0 text-secondary me-3">{{ request.user }}</p>
            <a href="#" class="btn btn-outline-danger btn-sm">Logout</a>
            {% else %}
            <div class="p-2">
                <a href="#" class="btn btn-outline-primary btn-sm">Login</a>
                <a href="#" class="btn btn-outline-primary btn-sm">SignUp</a>
            </div>
            {% endif %}
        </div>
    </div>
</header>

leetcode/templates/assist/message.html
{% if messages %}
{% for message in messages %}
<div class="p-2 alert alert-warning">
    {{ message }}
</div> 
{% endfor %}
{% endif %}

leetcode/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stack Overflow</title>

  <!-- Ajax -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>

  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <script src="https://cdn.tiny.cloud/1/55px6772jonjrhzyu0drrubwrwptayhfxvsx5060vi6l0ss7/tinymce/6/tinymce.min.js"
    referrerpolicy="origin"> </script>

  <!-- FontAwesome -->
  <script src="https://kit.fontawesome.com/cac7ba30d2.js" crossorigin="anonymous"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>

<body>
  {% include 'assist/header.html' %}
  {% include 'assist/message.html' %}
  {% block main %}

  {% endblock %}
</body>

</html>

leetcode/templates/code_editor/add_code.html
{% extends 'base.html' %}
{% block main %}
<div class="container-fluid" style="height: calc(100vh - 65px);">
    <div class="d-flex w-100">
        <div class="resize-h border-end p-3 bg-light" style="height: calc(100vh - 65px);">
            {% include 'code_editor/code_question_description.html' %}
        </div>
        <div class="p-3 w-50 bg-dark" style="flex-grow: 3;">
            {% include 'code_editor/editor.html' %}
        </div>
    </div>
</div>
{% endblock %}

leetcode/templates/code_editor/code_question_description.html
<!-- Tabs header -->

<div class="b-light">
    <div class="container d-flex justify-content-between align-content-center">
        <ul class="nav nav-pills" id="tabs-widget" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="description-tab" data-bs-toggle="pill" data-bs-target="#description"
                    type="button" role="tab" aria-controls="description" aria-selected="true">Description</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="discussion-tab" data-bs-toggle="pill" data-bs-target="#discussion"
                    type="button" role="tab" aria-controls="discussion" aria-selected="false">Discussion</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="solutions-tab" data-bs-toggle="pill" data-bs-target="#solutions"
                    type="button" role="tab" aria-controls="solutions" aria-selected="false">Solutions</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="submission-tab" data-bs-toggle="pill" data-bs-target="#submission"
                    type="button" role="tab" aria-controls="submission" aria-selected="false">Submission</button>
            </li>
        </ul>
    </div>
</div>
<hr>

<!-- Tabs Data -->
<div class="tab-content">
    <!-- Description content -->
    <div class="tab-pane show active" id="description" role="tabpanel" aria-labelledby="description-tab">
        <div class="row">
            <div class="col-1 mr-1">
                <!-- Question ID -->
                <p>1</p>
            </div>
            <div class="col-4">
                <!-- Question title -->
                <p>Two Sum</p>
            </div>
        </div>
        <div class="row d-flex justify-content-start mb-3">
            <div class="col-2 tag-icon">
                <p class="mr-1">Easy</p>
            </div>
            <div class="col-1">
                <i class="fa-regular fa-thumbs-up fs-5 cursor-pointer"></i>
            </div>
            <div class="col-1">
                <i class="fa-regular fa-thumbs-down fs-5 cursor-pointer"></i>
            </div>
        </div>
        <div class="row bg-light">
            <!-- Question Statement -->
            <p>
                Given array of integers <strong>nums</strong> and an integer <strong>target</strong>, return the two indices whose sum is equal to the <small>target.</small><br><br>
                You may assume each input have exactly one unique solution, and you may not use the same element twice. <br><br>
                You can return the answer in any order. <br><br>
                <code>
                    Input: nums = [1,2,3,4,5]  k = 5 <br>
                    Output: 4
                </code>
            </p>
        </div>
    </div>
    <!-- Discussion content -->
    <div class="tab-pane" id="discussion" role="tabpanel" aria-labelledby="discussion-tab">
        
    </div>
    <!-- Solutions content -->
    <div class="tab-pane" id="description" role="tabpanel" aria-labelledby="description-tab">
    </div>
    <!-- Submission content -->
    <div class="tab-pane" id="description" role="tabpanel" aria-labelledby="description-tab">
    </div>
</div>

leetcode/templates/code_editor/editor.html
<form id="coder_form" class="form" method="POST">
    {% csrf_token %}
    <div class="row d-flex justify-content-between">
        <div class="col mb-2">
            <button type="submit" class="btn btn-success my-0">C++</button>
            <button type="submit" class="btn btn-success my-0">Auto</button>
        </div>
        <div class="col">
            <i class="fa-solid fa-thumbs-up text-primary"></i>
            <i class="fa-solid fa-thumbs-down text-primary"></i>
        </div>
    </div>
    <div class="d-flex flex-column">
        <textarea class="form-control" data-editor="twilight" name="program" id="id_program" required></textarea>
    </div>
    <div class="d-flex flex-column bg-light" style="flex-grow: 3;">
        {% include 'code_editor/run_test.html' %}
    </div>
</form>

leetcode/templates/code_editor/run_test.html
<div class="b-light">
    <div class="container d-flex justify-content-start align-content-center">
        <ul class="nav nav-pills" id="tabs-widget" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="test_case-tab" data-bs-toggle="pill" data-bs-target="#test_case"
                    type="button" role="tab" aria-controls="test_case" aria-selected="true">Test Case</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="test_result-tab" data-bs-toggle="pill" data-bs-target="#test_result"
                    type="button" role="tab" aria-controls="test_result" aria-selected="false">Result</button>
            </li>
        </ul>
    </div>
</div>
<hr>

leetcode/templates/frontend/ask_question.html
{% extends 'base.html' %}
{% block main %}
<div class="container mt-5">
    <form action="{% url 'ask' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="">
                <h3>Title</h3>
            </label>
            <br><small class="form-text text-muted">Be specific, and give suitable title.</small>
            <input type="text" name="title" id="title" class="form-control" placeholder="Title"
                value="Custom close button in frameless window (ElectronJS)">
        </div>
        <div class="form-group mt-3">
            <label for="">
                <h3>Question</h3>
            </label>
            <br><small class="form-text text-muted">Ask question and be specific and describe you problem
                correctly.</small>
            <textarea type="text" name="question" id="question" class="form-control form-control-lg"
                placeholder="Question" rows="10">I created a frameless button, I want to have a close and minimize button, I created a button but how do I make window close after it's clicked? I want the script to be in separated file from index.js as well.</textarea>
        </div>
        <div class="form-group mt-3">
            <label for="">
                <h3>Tags</h3>
            </label>
            <br><small class="form-text text-muted">Suitble tags for question which describe the question in
                sort.</small>
            <input type="text" name="tags" id="tags" class="form-control form-control-lg" value="python3,ElectronJS">
        </div>
        <input type="submit" class="btn btn-outline-primary mt-3" value="Review Question">
    </form>
</div>

{% load static %}
<script src="{% static 'js/WYSIWYG.js' %}"></script>
{% endblock %}

leetcode/templates/frontend/home.html
{% extends 'base.html' %}
{% block main %}

<div class="container">
    {% include 'assist/ask_question_temp.html' %}

    <!-- Tabs  -->
    <div class="b-light">
        <div class="container d-flex justify-content-between align-content-center">
            <ul class="nav nav-pills" id="tabs-widget" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="recent-tab" data-bs-toggle="pill" data-bs-target="#recent"
                        type="button" role="tab" aria-controls="recent" aria-selected="true">Recent</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="most_viewed-tab" data-bs-toggle="pill" data-bs-target="#most_voted"
                        type="button" role="tab" aria-controls="most_voted" aria-selected="false">Most viewed</button>
                </li>
            </ul>
        </div>
    </div>
    <hr>

    <!-- Tabs Data -->
    <div class="tab-content">
        <div class="tab-pane show active" id="recent" role="tabpanel" aria-labelledby="recent-tab">
            {% for ques in questions.recently_created_list %}
            <div class="row mb-3 p-2 rounded-3" style="background: #eee;">
                <div class="col-10">
                    <div class="d-flex">
                        <small class="me-3">{{ ques.views }} views</small>
                        <!-- <small>{{ ques.getAnswersCount  ans</small> -->
                    </div>
                    <a href="{% url 'question' ques.id %}" 
                        class="text-decoration-none mb-2">{{ ques.title | title }}</a>
                    <p class="text-secondary mb-2 small">{{ ques.entity.text | safe }}</p>
                    <div class="d-flex">
                        {% for t in ques.getTags %}
                        <div class="tag-icon">
                            <p>{{ t.tag }}</p>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-2">
                    <a href="{% url 'profile' ques.entity.creator.id %}" class="btn btn-outline-primary btn-sm px-3">
                        {{ ques.entity.creator.username }}</a> <br>
                    <small>{{ ques.entity.creationDateTime | timesince }} ago</small>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="tab-pane" id="most_voted" role="tabpanel" aria-labelledby="most_viewed-tab">
            {% for ques in questions.most_views_list %}
            <div class="row mb-3 p-2 rounded-3" style="background: #eee;">
                <div class="col-10">
                    <div class="d-flex">
                        <small class="me-3">{{ ques.views }} views</small>
                    </div>
                    <a href="{% url 'question' ques.id %}" class="text-decoration-none mb-2">{{ ques.title | title }}</a>
                    <p class="text-secondary mb-2 small">{{ ques.entity.text | safe }}</p>
                    <div class="d-flex">
                        {% for t in ques.getTags %}
                        <div class="tag-icon">
                            <p>{{ t.tag }}</p>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-2">
                    <a href="{% url 'profile' ques.entity.creator.id %}" class="btn btn-outline-primary btn-sm px-3">
                        {{ ques.entity.creator.username }}</a> <br>
                    <small>{{ ques.entity.creationDateTime | timesince }} ago</small>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

leetcode/templates/frontend/login.html
{% extends 'base.html' %}
{% block main %}
<div class="container col-10 col-md-4 py-5 mt-5 px-4 rounded-4" style="background: #f1f1f1;">
    <h3 class="text-center">Login</h3><br>
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="user_name">User name</label><br>
            <input type="text" class="form-control" id="user_name" name="user_name" required><br>
        </div>
        <div class="form-group">
            <label for="password">Password</label><br>
            <input type="password" class="form-control" id="password" name="password" required><br>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit" id="submit-btn" name="submit-btn">
            <a href="{% url 'signup' %}" class="ms-3 text-decoration-none">SignUp</a>
        </div>
    </form>
    <hr>
    <ul>
        <li><a href="#">Forgot Password</a></li>
        <li><a href="#">Forgot Username</a></li>
        <li><a href="#">Resend activation code</a></li>
    </ul>
</div>    

{% endblock %}

leetcode/templates/frontend/profile.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    <table class="table table-bordered mt-5">
        <tr scope="row">
            <td>User Name</td>
            <td>{{ user.user.username }}</td>
        </tr>
        <tr scope="row">
            <td>First Name</td>
            <td>{{ user.user.first_name }}</td>
        </tr>
        <tr scope="row">
            <td>Last Name</td>
            <td>{{ user.user.last_name }}</td>
        </tr>
        <tr scope="row">
            <td>Email</td>
            <td>{{ user.user.email }}</td>
        </tr>
        <tr scope="row">
            <td>Status</td>
            <td>{{ user.account_state }}</td>
        </tr>
        <tr scope="row">
            <td>Reputation</td>
            <td>{{ user.reputation }}</td>
        </tr>    
    </table>
</div>
{% endblock %}

leetcode/templates/frontend/search_result.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    {% include 'assist/ask_question_temp.html' %}
    {% if count == 0 %}
    <p>No result found</p>
    {% else %}
    {% for ques in questions %}
    <div class="row mt-4 mb-3 p-2 rounded-3" style="background: #eee;">
        <div class="col-10">
            <div class="d-flex">
                <small class="me-3">{{ ques.views }} views</small>
                <!-- <small>{{ ques.getAnswersCount  ans</small> -->
            </div>
            <a href="{% url 'question' ques.id %}" class="text-decoration-none mb-2">{{ ques.title | title }}</a>
            <p class="text-secondary mb-2 small">{{ ques.entity.text | safe }}</p>
            <div class="d-flex">
                {% for t in ques.getTags %}
                <div class="tag-icon">
                    <p>{{ t.tag }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-2">
            <a href="{% url 'profile' ques.entity.creator.id %}" class="btn btn-outline-primary btn-sm px-3">
                {{ ques.entity.creator.username }}</a> <br>
            <small>{{ ques.entity.creationDateTime | timesince }} ago</small>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

leetcode/templates/frontend/signup.html
{% extends 'base.html' %}
{% block main %}

<div class="container col-10 col-md-4 py-3 mt-3 px-4 rounded-4" style="background: #f1f1f1;">
    <h3 class="text-center">Create Account</h3><br>
    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="user_name">User Name</label><br>
            <input type="text" class="form-control" id="user_name" name="user_name" placeholder="Enter user name" required><br>
        </div>
        <div class="form-group">
            <label for="full_name">Name</label><br>
            <input type="text" class="form-control" id="full_name" name="full_name" placeholder="Enter full name" required><br>
        </div>
        <div class="form-group">
            <label for="email">Email</label><br>
            <input type="email" class="form-control" id="email" name="email" placeholder="xyz@example.com" required><br>
        </div>
        <div class="form-group">
            <label for="password">Password</label><br>
            <input type="password" class="form-control" id="password" name="password" required>
            <ul class="mt-2">
                <li><p class="text-secondary mb-0" style="font-size: 13px;">Your password must contain atleast 8 characters</p></li>
                <li><p class="text-secondary mb-0" style="font-size: 13px;">Your password must contain atleast 1 uppercase character</p></li>
                <li><p class="text-secondary mb-0" style="font-size: 13px;">Your password must contain atleast 1 lowercase character</p></li>
                <li><p class="text-secondary mb-0" style="font-size: 13px;">Your password must contain atleast 1 digit</p></li>
                <li><p class="text-secondary mb-0" style="font-size: 13px;">Your password must contain atleast 1 special character</p></li>
            </ul>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success px-4" value="Submit" id="submit-btn" name="submit-btn">
        </div>
    </form>
</div>    

{% endblock %}

leetcode/templates/frontend/view_question.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    {% load static %}
    {% include 'assist/ask_question_temp.html' %}
    <h2>{{ question.title }}</h2>
    <div class="row text-secondary">
        <div class="col-3">
            <small>Asked {{ question.entity.creationDateTime | timesince }} ago</small>
        </div>
        <div class="col-2">
            <p>Views {{ question.views | title }}</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-1">
            <div class="row-sm">
                <form method="post" id="upvote_form">
                    {% csrf_token %}
                    {% if votes_ud == 0 %}
                    <p class="mb-0 already_upvoted" id="upvote_btn"><i
                            class="fa-solid fa-thumbs-up fs-5 cursor-pointer text-primary"></i></p>
                    {% else %}
                    <p class="mb-0" id="upvote_btn"><i class="fa-regular fa-thumbs-up fs-5 cursor-pointer"></i></p>
                    {% endif %}
                </form>
            </div>
            <div class="row">
                <p class="mt-1 mb-1" id="votes_counter">{{ question.votes_count }}</p>
            </div>
            <div class="row-sm">
                <form method="post" id="downvote_form">
                    {% csrf_token %}
                    {% if votes_ud == 1 %}
                    <p class="mb-0 already_downvoted" id="downvote_btn"><i
                            class="fa-solid fa-thumbs-down fs-5 text-primary cursor-pointer"></i></p>
                    {% else %}
                    <p class="mb-0" id="downvote_btn"><i class="fa-regular fa-thumbs-down fs-5 cursor-pointer"></i></p>
                    {% endif %}
                </form>
            </div>
        </div>
        <div class="col-10 ml-3">
            <div class="row bg-light" style="min-height: 250px;">
                {{ question.entity.text | safe }}
            </div>
            <div class="row">
                <div class="d-flex">
                    {% for t in question.getTags %}
                    <div class="tag-icon">
                        <p>{{ t.tag }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <form action="{% url 'comment' question.id %}" method="POST">
        {% csrf_token %}
        <div class="mt-5" style="max-height: 200px;">
            <textarea name="comment" id="comment" height="100px"></textarea>
            <div class="d-flex justify-content-end my-3">
                <input type="submit" class="btn btn-outline-primary" value="Comment">
            </div>
        </div>
    </form>

    <form action="{% url 'answer' question.id %}" method="POST">
        {% csrf_token %}
        <div class="mt-5">
            <textarea name="answer" id="answer" cols="30" rows="5"></textarea>
            <div class="d-flex justify-content-end my-3">
                <input type="submit" class="form-control btn btn-outline-primary" value="Answer">
            </div>
        </div>
    </form>

    {% for cmnt in question.getComments %}
    <div class="row">
        <h3>Comment</h3>
        <div class="col-2">
            <a href="{% url 'profile' cmnt.entity.creator.id %}" class="btn btn-outline-primary btn-sm px-3">
                {{ cmnt.entity.creator.username }}</a>
            <small>{{ cmnt.entity.creationDateTime | timesince }} ago</small>
        </div>
        <div class="col-10">
            <p>{{ cmnt.entity.text | safe }}</p>
        </div>
    </div>
    <hr>
    {% endfor %}


    {% for ans in question.getAnswers %}
    <div class="row">
        <h3>Answer</h3>
        <div class="col-2">
            <a href="{% url 'profile' ans.entity.creator.id %}" class="btn btn-outline-primary btn-sm px-3">
                {{ ans.entity.creator.username }}</a>
            <small>{{ ans.entity.creationDateTime | timesince }} ago</small>
        </div>
        <div class="col-10">
            <p>{{ ans.entity.text | safe }}</p>
        </div>
    </div>
    <hr>
    {% endfor %}


</div>
<script src="{% static 'js/WYSIWYG.js' %}"></script>
<script>
function sub_vote(){
    var new_val = Number.parseInt($('#votes_counter').val()) - 1;
    $('#votes_counter').val(new_val);
}

function add_vote() {
    var new_val = Number.parseInt($('#votes_counter').val()) + 1
    $('#votes_counter').val(new_val);
}

$('#upvote_btn').click(function () {
    var id = '{{ question.id }}';
    var vote_type = 'up';
    var vote_action = 'vote'
    var csrfmiddlewaretoken = $('#upvote_form input[name=csrfmiddlewaretoken]').val()

    if ($(this).hasClass('already_upvoted')) {
        vote_action = 'recall-vote'
        $.post('/question/vote', { id: id, type: vote_type, action: vote_action, csrfmiddlewaretoken: csrfmiddlewaretoken }, function (response) {
            if (response === 'ok') {
                $('#upvote_btn').find('i').removeClass('text-primary').toggleClass('fa-solid fa-regular');
                $('#upvote_btn').removeClass('already_upvoted');
                sub_vote()
            }
        });
    } else {
        $.post('/question/vote', { id: id, type: vote_type, action: vote_action, csrfmiddlewaretoken: csrfmiddlewaretoken }, function (response) {
            if (response === 'ok') {
                $('#upvote_btn').find('i').addClass('text-primary').toggleClass('fa-regular fa-solid');
                $('#upvote_btn').addClass('already_upvoted');
                add_vote()
                if ($("#downvote_btn").hasClass('already_downvoted')) {
                    $('#downvote_btn').find('i').removeClass('text-primary').toggleClass('fa-solid fa-regular');
                    $('#downvote_btn').removeClass('already_downvoted');
                    add_vote()
                }
            }
        });
    }
});

// ------------------------
$('#downvote_btn').click(function () {
    var id = '{{ question.id }}';
    var vote_type = 'down';
    var csrfmiddlewaretoken = $('#downvote_form input[name=csrfmiddlewaretoken]').val()
    var vote_action = 'vote'

    if ($(this).hasClass('already_downvoted')) {
        vote_action = 'recall-vote'
        $.post('/question/vote', { id: id, type: vote_type, action: vote_action, csrfmiddlewaretoken: csrfmiddlewaretoken }, function (response) {
            if (response === 'ok') {
                $('#downvote_btn').find('i').removeClass('text-primary').toggleClass('fa-solid fa-regular');
                $('#downvote_btn').removeClass('already_downvoted');
                add_vote()
            }
        });
    } else {
        $.post('/question/vote', { id: id, type: vote_type, action: vote_action, csrfmiddlewaretoken: csrfmiddlewaretoken }, function (response) {
            if (response === 'ok') {
                $('#downvote_btn').find('i').addClass('text-primary').toggleClass('fa-regular fa-solid');
                $('#downvote_btn').addClass('already_downvoted');
                sub_vote()
                if ($('#upvote_btn').hasClass('already_upvoted')) {
                    $('#upvote_btn').find('i').removeClass('text-primary').toggleClass('fa-solid fa-regular');
                    $('#upvote_btn').removeClass('already_upvoted');
                    sub_vote()
                }
            }
        });
    }
})
</script>
{% endblock %}